<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:html="http://www.w3.org/1999/xhtml"
    xmlns:tei="http://www.tei-c.org/ns/1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    exclude-result-prefixes="tei html xs"
    version="2.0">
    <!-- import base conversion style -->

  

   <xsl:output method="xhtml" omit-xml-declaration="yes"/>



<xsl:template match="/">
  <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <!--THIS FILE IS GENERATED FROM AN XML MASTER. DO NOT EDIT (5)-->
      <title>Names used in your document</title>
      <meta name="author" content="Lou Burnard Consulting" />
      <meta name="generator" content="Text Encoding Initiative Consortium XSLT stylesheets" />
      <meta name="DC.Title" content="An exercise in web publishing using TEI-Boilerplate" />
      <meta name="DC.Type" content="Text" />
      <meta name="DC.Format" content="text/html" />
      <!--<link href="http://www.tei-c.org/release/xml/tei/stylesheet/tei.css" rel="stylesheet"
        type="text/css" />
      <link rel="stylesheet" media="print" type="text/css"
        href="http://www.tei-c.org/release/xml/tei/stylesheet/tei-print.css" />-->
    </head>
    <body class="simple" id="TOP"><div class="stdheader autogenerated">
      <h1 class="maintitle">The following names were found </h1>
  
  <table class="sort">
    <thead>
      <tr><th>Key</th><th>Occurrences</th><th>persNames</th></tr>
    </thead>
    <xsl:for-each-group select="//tei:text//tei:persName" group-by="tei:Maybe(@ref)">
      <xsl:sort select="."/>
      <tr>
	<td><xsl:value-of select="current-grouping-key()"/></td>
	<td><xsl:value-of select="count(current-group())"/></td>
	<td><xsl:for-each-group select="current-group()" group-by=".">
	  <xsl:sort select="."/>
	  <xsl:value-of select="current-grouping-key()"/>
	  <xsl:text> (</xsl:text>
	  <xsl:value-of select="count(current-group())"/>
	  <xsl:text>) </xsl:text>
	</xsl:for-each-group>
	</td>
      </tr>
    </xsl:for-each-group>
  </table>
  <table class="sort">
    <thead>
      <tr><th>Key</th><th>Occurrences</th><th>placeNames</th></tr>
    </thead>
    <xsl:for-each-group select="//tei:text//tei:placeName" group-by="tei:Maybe(@ref)">
      <xsl:sort select="."/>
      <tr>
        <td><xsl:value-of select="current-grouping-key()"/></td>
        <td><xsl:value-of select="count(current-group())"/></td>
        <td><xsl:for-each-group select="current-group()" group-by=".">
          <xsl:sort select="."/>
          <xsl:value-of select="current-grouping-key()"/>
          <xsl:text> (</xsl:text>
          <xsl:value-of select="count(current-group())"/>
          <xsl:text>) </xsl:text>
        </xsl:for-each-group>
        </td>
      </tr>
    </xsl:for-each-group>
  </table>
    </div></body></html>
  
</xsl:template>

  <!--<xsl:template name="javascriptHook">
    <script src="jquery-1.10.2.min.js" type="text/javascript">
      <xsl:comment>brk</xsl:comment>
    </script>
    <script src="jquery-ui-1.10.3.custom.js" type="text/javascript">
      <xsl:comment>brk</xsl:comment>
    </script>
    <script src="jquery.dataTables.min.js" type="text/javascript">
      <xsl:comment>brk</xsl:comment>
    </script>
    <script type="text/javascript">
      $(document).ready(function() {
	var oTable = $('.sort').dataTable( {
	"sPaginationType": "full_numbers",
	"bPaginate": true,
	"bLengthChange": true,
	"bAutoWidth": false,
	"bFilter": true,
	"bSort": true,
	"bInfo": true,
	"aaSorting": [ ],
	"bScrollCollapse": true,
	"bJQueryUI": true,
	"sDom": 'flprtip'})});
    </script>
  </xsl:template>
-->
  <xsl:function name="tei:Maybe" as="xs:string*">
    <xsl:param name="val"/>
    <xsl:choose>
      <xsl:when test="string-length($val) gt 1">
        <xsl:value-of select="$val"/></xsl:when>
      <xsl:otherwise><xsl:text>[none]</xsl:text>
       
      </xsl:otherwise>
    </xsl:choose>
  </xsl:function>

</xsl:stylesheet>
